server:
  port: 1000
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      exclude: resources/**,static/**,public/**,templates/**
  datasource:
    username: sa
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
